export interface Country {
  name: string;
  dialCode: string;
  flag: string;
}

export const PINNED_COUNTRIES: Country[] = [
  { name: "Colombia", dialCode: "57", flag: "🇨🇴" },
  { name: "Spain", dialCode: "34", flag: "🇪🇸" },
  { name: "United States", dialCode: "1", flag: "🇺🇸" },
];

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", dialCode: "93", flag: "🇦🇫" },
  { name: "Albania", dialCode: "355", flag: "🇦🇱" },
  { name: "Algeria", dialCode: "213", flag: "🇩🇿" },
  { name: "Argentina", dialCode: "54", flag: "🇦🇷" },
  { name: "Australia", dialCode: "61", flag: "🇦🇺" },
  { name: "Austria", dialCode: "43", flag: "🇦🇹" },
  { name: "Belgium", dialCode: "32", flag: "🇧🇪" },
  { name: "Bolivia", dialCode: "591", flag: "🇧🇴" },
  { name: "Brazil", dialCode: "55", flag: "🇧🇷" },
  { name: "Canada", dialCode: "1", flag: "🇨🇦" },
  { name: "Chile", dialCode: "56", flag: "🇨🇱" },
  { name: "China", dialCode: "86", flag: "🇨🇳" },
  { name: "Colombia", dialCode: "57", flag: "🇨🇴" },
  { name: "Costa Rica", dialCode: "506", flag: "🇨🇷" },
  { name: "Cuba", dialCode: "53", flag: "🇨🇺" },
  { name: "Czech Republic", dialCode: "420", flag: "🇨🇿" },
  { name: "Denmark", dialCode: "45", flag: "🇩🇰" },
  { name: "Dominican Republic", dialCode: "1", flag: "🇩🇴" },
  { name: "Ecuador", dialCode: "593", flag: "🇪🇨" },
  { name: "Egypt", dialCode: "20", flag: "🇪🇬" },
  { name: "El Salvador", dialCode: "503", flag: "🇸🇻" },
  { name: "Finland", dialCode: "358", flag: "🇫🇮" },
  { name: "France", dialCode: "33", flag: "🇫🇷" },
  { name: "Germany", dialCode: "49", flag: "🇩🇪" },
  { name: "Greece", dialCode: "30", flag: "🇬🇷" },
  { name: "Guatemala", dialCode: "502", flag: "🇬🇹" },
  { name: "Honduras", dialCode: "504", flag: "🇭🇳" },
  { name: "Hungary", dialCode: "36", flag: "🇭🇺" },
  { name: "India", dialCode: "91", flag: "🇮🇳" },
  { name: "Indonesia", dialCode: "62", flag: "🇮🇩" },
  { name: "Iran", dialCode: "98", flag: "🇮🇷" },
  { name: "Iraq", dialCode: "964", flag: "🇮🇶" },
  { name: "Ireland", dialCode: "353", flag: "🇮🇪" },
  { name: "Israel", dialCode: "972", flag: "🇮🇱" },
  { name: "Italy", dialCode: "39", flag: "🇮🇹" },
  { name: "Japan", dialCode: "81", flag: "🇯🇵" },
  { name: "Jordan", dialCode: "962", flag: "🇯🇴" },
  { name: "Kenya", dialCode: "254", flag: "🇰🇪" },
  { name: "South Korea", dialCode: "82", flag: "🇰🇷" },
  { name: "Kuwait", dialCode: "965", flag: "🇰🇼" },
  { name: "Lebanon", dialCode: "961", flag: "🇱🇧" },
  { name: "Libya", dialCode: "218", flag: "🇱🇾" },
  { name: "Malaysia", dialCode: "60", flag: "🇲🇾" },
  { name: "Mexico", dialCode: "52", flag: "🇲🇽" },
  { name: "Morocco", dialCode: "212", flag: "🇲🇦" },
  { name: "Netherlands", dialCode: "31", flag: "🇳🇱" },
  { name: "New Zealand", dialCode: "64", flag: "🇳🇿" },
  { name: "Nicaragua", dialCode: "505", flag: "🇳🇮" },
  { name: "Nigeria", dialCode: "234", flag: "🇳🇬" },
  { name: "Norway", dialCode: "47", flag: "🇳🇴" },
  { name: "Pakistan", dialCode: "92", flag: "🇵🇰" },
  { name: "Panama", dialCode: "507", flag: "🇵🇦" },
  { name: "Paraguay", dialCode: "595", flag: "🇵🇾" },
  { name: "Peru", dialCode: "51", flag: "🇵🇪" },
  { name: "Philippines", dialCode: "63", flag: "🇵🇭" },
  { name: "Poland", dialCode: "48", flag: "🇵🇱" },
  { name: "Portugal", dialCode: "351", flag: "🇵🇹" },
  { name: "Puerto Rico", dialCode: "1", flag: "🇵🇷" },
  { name: "Romania", dialCode: "40", flag: "🇷🇴" },
  { name: "Russia", dialCode: "7", flag: "🇷🇺" },
  { name: "Saudi Arabia", dialCode: "966", flag: "🇸🇦" },
  { name: "South Africa", dialCode: "27", flag: "🇿🇦" },
  { name: "Spain", dialCode: "34", flag: "🇪🇸" },
  { name: "Sweden", dialCode: "46", flag: "🇸🇪" },
  { name: "Switzerland", dialCode: "41", flag: "🇨🇭" },
  { name: "Thailand", dialCode: "66", flag: "🇹🇭" },
  { name: "Turkey", dialCode: "90", flag: "🇹🇷" },
  { name: "Ukraine", dialCode: "380", flag: "🇺🇦" },
  { name: "United Arab Emirates", dialCode: "971", flag: "🇦🇪" },
  { name: "United Kingdom", dialCode: "44", flag: "🇬🇧" },
  { name: "United States", dialCode: "1", flag: "🇺🇸" },
  { name: "Uruguay", dialCode: "598", flag: "🇺🇾" },
  { name: "Venezuela", dialCode: "58", flag: "🇻🇪" },
  { name: "Vietnam", dialCode: "84", flag: "🇻🇳" },
];
