import { render, RenderOptions } from "@testing-library/react";
import { NextIntlClientProvider } from "next-intl";
import React from "react";

// Minimal en messages covering all namespaces used in tests
const testMessages = {
  auth: {
    login: {
      emailLabel: "Email",
      emailPlaceholder: "you@example.com",
      passwordLabel: "Password",
      hidePassword: "Hide password",
      showPassword: "Show password",
      forgotPassword: "Forgot your password?",
      submit: "Sign In",
      submitting: "Signing in...",
      errorAccountLocked: "Account locked until {date}",
      errorEmailNotVerified: "Please verify your email address before logging in",
      errorAccountSetupPending: "Your account isn't set up yet. Check your email for the setup link.",
      accountSetupPendingResend: "Didn't receive it?",
      accountSetupPendingLink: "Request a new setup link",
      errorNetwork: "Unable to connect to server",
    },
    register: {
      firstNameLabel: "First Name *",
      lastNameLabel: "Last Name *",
      emailLabel: "Email *",
      dateOfBirthLabel: "Date of Birth *",
      epsLabel: "EPS *",
      tutorInfoLegend: "Tutor Information (required for minors)",
      tutorFullNameLabel: "Tutor Full Name *",
      tutorRelationshipLabel: "Relationship *",
      tutorRelationshipPlaceholder: "e.g., Mother, Father, Legal Guardian",
      tutorPhoneLabel: "Tutor Phone *",
      successTitle: "Registration Successful!",
      successMessage: "Check your email to set up your account password.",
      goToLogin: "Go to Login",
      submit: "Create Account",
      submitting: "Creating account...",
      signInText: "Already have an account?",
      signInLink: "Sign in",
      errorNetwork: "Unable to connect to server",
    },
    forgotPassword: {
      emailLabel: "Email address",
      emailPlaceholder: "you@example.com",
      submit: "Send Reset Link",
      submitting: "Sending...",
      backToLogin: "Back to Login",
      successTitle: "Check your email",
      successMessage: "If an account exists with {email}, we've sent a password reset link. The link expires in 30 minutes.",
    },
    resetPassword: {
      newPasswordLabel: "New Password",
      confirmPasswordLabel: "Confirm New Password",
      submit: "Reset Password",
      submitting: "Resetting...",
      errorMismatch: "Passwords do not match",
      errorNetwork: "Unable to connect to server",
    },
    passwordPolicy: {
      minLength: "At least 8 characters",
      uppercase: "At least 1 uppercase letter",
      digit: "At least 1 digit",
      special: "At least 1 special character",
    },
    setupAccount: {
      pageTitle: "Set up your account",
      pageSubtitle: "Choose a password to activate your account.",
      pageLoading: "Loading...",
      labelNewPassword: "New Password",
      labelConfirmPassword: "Confirm New Password",
      submit: "Set Password",
      submitting: "Setting up...",
      errorPasswordMismatch: "Passwords do not match.",
      errorPasswordInvalid: "Password does not meet the requirements.",
      errorGeneric: "Something went wrong. Please try again.",
      successTitle: "Account Setup Complete",
      successMessage: "Your account is ready! You can now log in.",
      successLogIn: "Log In",
      expiredTitle: "Setup Link Expired",
      expiredMessage: "This setup link has expired or is no longer valid.",
      expiredRequestNew: "Request a New Link",
      resendHint: "Enter your email address and we'll send you a new setup link.",
      resendEmailLabel: "Email address",
      resendEmailPlaceholder: "you@example.com",
      resendSubmit: "Send New Link",
      resendSubmitting: "Sending...",
      resendDoneTitle: "Email Sent",
      resendDoneMessage: "A new setup link has been sent to your email.",
    },
  },
  common: {
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    loading: "Loading...",
    noResults: "No results found",
    previous: "Previous",
    next: "Next",
    page: "Page",
    of: "of",
    totalCount: "{count} total",
    active: "Active",
    inactive: "Inactive",
    search: "Search",
    clear: "Clear",
    actions: "Actions",
    confirm: "Confirm",
    back: "Back",
    close: "Close",
    create: "Create",
    view: "View",
    deactivate: "Deactivate",
    reactivate: "Reactivate",
    deactivating: "Deactivating...",
    reactivating: "Reactivating...",
    saving: "Saving...",
    creating: "Creating...",
    all: "All",
    yes: "Yes",
    no: "No",
    unexpectedError: "An unexpected error occurred. Please try again.",
  },
  validation: {
    firstName: {
      required: "First name is required.",
      maxLength: "First name must be at most 100 characters.",
    },
    lastName: {
      required: "Last name is required.",
      maxLength: "Last name must be at most 100 characters.",
    },
    email: {
      required: "Email is required.",
      invalid: "Please enter a valid email address.",
      maxLength: "Email must be at most 255 characters.",
    },
    phone: {
      required: "Phone number is required.",
      invalid: "Enter a valid WhatsApp number in E.164 format, e.g. +573001234567",
      maxLength: "Phone number must be at most 20 characters.",
    },
    identityNumber: {
      required: "Identity number is required.",
      maxLength: "Identity number must be at most 30 characters.",
    },
    documentType: { required: "Document type is required." },
    documentNumber: {
      required: "Document number is required.",
      maxLength: "Document number must be at most 30 characters.",
    },
  },
  pagination: {
    previous: "Previous",
    next: "Next",
    summary: "Page {current} of {total} ({count} total)",
  },
  professors: {
    pageTitle: "Professors",
    filterAll: "All",
    filterActive: "Active",
    filterDeactivated: "Deactivated",
    listLoading: "Loading professors...",
    listEmpty: "No professors match the current filter.",
    addButton: "Add Professor",
    colName: "Name",
    colEmail: "Email",
    colPhone: "Phone",
    colDocument: "Document",
    colStatus: "Status",
    colCreated: "Created",
    colActions: "Actions",
    modalDeactivateTitle: "Deactivate Professor",
    modalDeactivateConfirm: "Are you sure you want to deactivate {name}?",
    modalDeactivateHint: "The account will be disabled immediately. You can re-activate it at any time.",
    modalCancelButton: "Cancel",
    modalDeactivateButton: "Deactivate",
    modalDeactivatingButton: "Deactivating...",
    formFirstNameLabel: "First Name *",
    formFirstNamePlaceholder: "e.g. Carlos",
    formLastNameLabel: "Last Name *",
    formLastNamePlaceholder: "e.g. Martinez",
    formEmailLabel: "Email *",
    formEmailPlaceholder: "e.g. carlos@example.com",
    formPhoneLabel: "Phone Number (must be valid for WhatsApp)",
    formPhonePlaceholder: "e.g. +573001234567",
    formSaveButton: "Save Changes",
    formCreateButton: "Create Professor",
    formSavingButton: "Saving...",
    formCreatingButton: "Creating...",
    detailFirstName: "First Name",
    detailLastName: "Last Name",
    detailEmail: "Email",
    detailPhone: "Phone Number",
    detailDocType: "Document Type",
    detailDocNumber: "Document Number",
    detailStatus: "Status",
    detailCreatedAt: "Created At",
    detailCreatedBy: "Created By",
    detailUpdatedAt: "Last Updated",
    detailUpdatedBy: "Updated By",
    detailEditButton: "Edit",
    detailDeactivateButton: "Deactivate Professor",
    detailDeactivatingButton: "Deactivating...",
    detailReactivateButton: "Reactivate Professor",
    detailReactivatingButton: "Reactivating...",
    detailDeactivateConfirm: "Are you sure you want to deactivate this professor?",
    detailDeactivateModalTitle: "Confirm Deactivation",
    detailCancelButton: "Cancel",
    detailSuccessFeedback: "Professor has been {action} successfully.",
    detailErrorFeedback: "Failed to {action} professor. Please try again.",
  },
  commonFields: {
    documentTypeLabel: "Document Type *",
    documentNumberLabel: "Document Number *",
    documentNumberPlaceholder: "e.g. 1234567890",
  },
  programs: {
    pageTitle: "Programs",
    createButton: "Create New Program",
    filterStatusLabel: "Status:",
    filterAll: "All",
    filterActive: "Active",
    filterInactive: "Inactive",
    listLoading: "Loading programs...",
    listEmpty: "No programs found",
    colName: "Name",
    colStatus: "Status",
    colCreatedAt: "Created At",
    detailLoadingText: "Loading program details...",
    detailBreadcrumb: "Programs",
    detailTabDetails: "Details",
    detailTabPlans: "Plans",
    detailTabClasses: "Classes",
    detailName: "Name",
    detailStatus: "Status",
    detailCreatedAt: "Created At",
    detailCreatedBy: "Created By",
    detailLastUpdated: "Last Updated",
    detailUpdatedBy: "Updated By",
    detailEditButton: "Edit",
    detailDeactivateButton: "Deactivate Program",
    detailDeactivatingButton: "Deactivating...",
    detailConfirmDeactivate: "Are you sure you want to deactivate this program?",
    detailConfirmDeactivateButton: "Confirm Deactivation",
    detailCancelButton: "Cancel",
    detailReactivateButton: "Reactivate Program",
    detailReactivatingButton: "Reactivating...",
    detailSuccessFeedback: "Program has been {action} successfully.",
    detailErrorFeedback: "Failed to {action} program. Please try again.",
    plansTitle: "Plans",
    plansAddButton: "Add Plan",
    plansEmpty: "No plans configured yet. Add a plan to define pricing tiers for this program.",
    plansAddFirstButton: "Add First Plan",
    plansColName: "Name",
    plansColModality: "Modality",
    plansColCost: "Cost",
    plansColHours: "Hours",
    plansColManager: "Manager",
    plansColStatus: "Status",
    plansColActions: "Actions",
    plansView: "View",
    modalityHoursBased: "Hours Based",
    modalityClassesPerWeek: "Classes per Week",
    formNameLabel: "Name",
    formNamePlaceholderHours: "e.g., 4 Hours",
    formNamePlaceholderSchedule: "e.g., Mon/Wed/Thu Evening",
    formModalityLabel: "Modality",
    formModalityCannotChange: "Modality cannot be changed after creation.",
    formCostLabel: "Cost (COP)",
    formManagerLabel: "Manager",
    formManagerLoading: "Loading managers...",
    formManagerPlaceholder: "Select a manager...",
    formManagerNone: "No active managers available for this program.",
    formHoursLabel: "Hours",
    formHoursHint: "Number of hours included in this plan.",
    formScheduleLabel: "Schedule Entries",
    formScheduleAddEntry: "+ Add Entry",
    formScheduleEmpty: "No schedule entries. Click \"Add Entry\" to define class times.",
    formScheduleTo: "to",
    formScheduleRemove: "Remove",
    formCancelButton: "Cancel",
    formUpdateButton: "Update Plan",
    formCreatePlanButton: "Create Plan",
    formUpdatingButton: "Updating...",
    formCreatingButton: "Creating...",
    formSaveButton: "Save Changes",
    formSavingButton: "Saving...",
    formCreateProgramButton: "Create Program",
    formNameProgramLabel: "Name",
    formNameProgramRequired: "Name is required.",
    formNameProgramMaxLength: "Name must be at most 150 characters.",
    formNameProgramPlaceholder: "e.g. Kids Football",
    formPlanCostError: "Cost must be a positive number.",
    formPlanHoursError: "Hours must be a positive integer.",
    formPlanScheduleError: "At least one schedule entry is required.",
    formPlanManagerError: "Manager is required.",
    newBreadcrumbNew: "New",
    newPageTitle: "Create New Program",
    editPageTitle: "Edit Program",
    editLoadingText: "Loading program...",
    planNewBreadcrumb: "New Plan",
    planNewPageTitle: "Add New Plan",
    planNewLoadingText: "Loading program...",
    planDetailBreadcrumb: "Plan",
    planDetailLoadingText: "Loading plan details...",
    planDetailModality: "Modality",
    planDetailManagerId: "Manager ID",
    planDetailHours: "Hours",
    planDetailCreatedAt: "Created At",
    planDetailCreatedBy: "Created By",
    planDetailLastUpdated: "Last Updated",
    planDetailUpdatedBy: "Updated By",
    planDetailEditButton: "Edit",
    planDetailScheduleTitle: "Schedule",
    planDetailDeactivateButton: "Deactivate Plan",
    planDetailDeactivatingButton: "Deactivating...",
    planDetailConfirmDeactivate: "Are you sure you want to deactivate this plan?",
    planDetailConfirmDeactivateButton: "Confirm Deactivation",
    planDetailCancelButton: "Cancel",
    planDetailReactivateButton: "Reactivate Plan",
    planDetailReactivatingButton: "Reactivating...",
    planDetailSuccessFeedback: "Plan has been {action} successfully.",
    planDetailErrorFeedback: "Failed to {action} plan. Please try again.",
    classesPageTitle: "Classes",
    classDetailLoadingText: "Loading class details...",
    classEditPageTitle: "Edit Class",
    classEditLoadingText: "Loading class...",
    classNewPageTitle: "Create New Class",
  },
  classes: {
    pageTitle: "All Classes",
    filterProgramLabel: "Program:",
    filterProgramPlaceholder: "Filter by program name...",
    filterLevelLabel: "Level:",
    filterAll: "All",
    filterStatusLabel: "Status:",
    filterActive: "Active",
    filterInactive: "Inactive",
    listLoading: "Loading classes...",
    listEmpty: "No classes found",
    listEmptyAction: "Create your first class",
    colName: "Name",
    colProgram: "Program",
    colLevel: "Level",
    colType: "Type",
    colProfessor: "Professor",
    colMaxStudents: "Max Students",
    colStatus: "Status",
    colCreated: "Created",
    colUnassigned: "Unassigned",
    filterBeginnerOption: "Beginner",
    filterIntermediateOption: "Intermediate",
    filterAdvancedOption: "Advanced",
    detailName: "Name",
    detailLevel: "Level",
    detailType: "Type",
    detailMaxStudents: "Max Students",
    detailProfessor: "Professor",
    detailProfessorUnassigned: "Unassigned",
    detailStatus: "Status",
    detailSchedule: "Schedule",
    detailCreatedAt: "Created At",
    detailCreatedBy: "Created By",
    detailLastUpdated: "Last Updated",
    detailUpdatedBy: "Updated By",
    detailEditButton: "Edit",
    detailProfessorAssignmentTitle: "Professor Assignment",
    detailRemoveProfessorButton: "Remove Professor",
    detailRemoveProfessorConfirm: "Are you sure you want to remove the professor from this class?",
    detailRemovingButton: "Removing...",
    detailConfirmRemovalButton: "Confirm Removal",
    detailNoProfessor: "No professor assigned to this class.",
    detailDeactivateButton: "Deactivate Class",
    detailDeactivatingButton: "Deactivating...",
    detailConfirmDeactivate: "Are you sure you want to deactivate this class?",
    detailConfirmDeactivateButton: "Confirm Deactivation",
    detailCancelButton: "Cancel",
    detailReactivateButton: "Reactivate Class",
    detailReactivatingButton: "Reactivating...",
    detailClassSuccessFeedback: "Class has been {action} successfully.",
    detailClassErrorFeedback: "Failed to {action} class. Please try again.",
    detailRemoveProfessorSuccess: "Professor has been removed from this class successfully.",
    detailRemoveProfessorError: "Failed to remove professor. Please try again.",
    formClassNameLabel: "Class Name",
    formClassNamePlaceholder: "e.g. Kids Beginner Monday",
    formLevelLabel: "Level",
    formLevelPlaceholder: "Select a level",
    formLevelRequired: "Level is required.",
    formTypeLabel: "Class Type",
    formTypeRecurring: "Recurring",
    formTypeOneTime: "One-Time",
    formTypeRequired: "Type is required.",
    formMaxStudentsLabel: "Max Students",
    formMaxStudentsPlaceholder: "e.g. 20",
    formMaxStudentsRequired: "Max students is required.",
    formMaxStudentsMin: "Max students must be at least 1.",
    formProfessorLabel: "Professor",
    formProfessorLoading: "Loading professors...",
    formProfessorPlaceholder: "Select a professor",
    formProfessorRequired: "Professor is required.",
    formScheduleLabel: "Schedule",
    formScheduleDayLabel: "Day of Week",
    formScheduleDayPlaceholder: "Select day",
    formScheduleDateLabel: "Date",
    formScheduleStartLabel: "Start Time",
    formScheduleEndLabel: "End Time",
    formScheduleRemoveButton: "Remove",
    formScheduleAddEntry: "+ Add Schedule Entry",
    formScheduleRequired: "At least one schedule entry is required.",
    formScheduleTimesRequired: "All schedule entries must have start and end times.",
    formScheduleDayRequired: "Recurring classes require a day of the week for each entry.",
    formScheduleDateRequired: "One-time classes require a specific date.",
    formScheduleOneTimeMax: "One-time classes can only have one schedule entry.",
    formSaveButton: "Save Changes",
    formSavingButton: "Saving...",
    formCreateButton: "Create Class",
    formCreatingButton: "Creating...",
    formNameRequired: "Name is required.",
    formNameMaxLength: "Name must be at most 100 characters.",
    professorAssignmentTitle: "Professor Assignment",
    professorCurrentLabel: "Current Professor",
    professorIdLabel: "Professor ID",
    professorIdPlaceholder: "UUID of the professor",
    professorAssignButton: "Assign Professor",
    professorAssigningButton: "Assigning...",
    professorConfirmAssignButton: "Confirm Assignment",
    professorConfirmAssignQuestion: "Are you sure you want to assign this professor to the class?",
    professorRemoveButton: "Remove Professor",
    professorRemovingButton: "Removing...",
    professorConfirmRemovalButton: "Confirm Removal",
    professorConfirmRemoveQuestion: "Are you sure you want to remove the professor from this class?",
    professorCancelButton: "Cancel",
    professorAssignSuccess: "Professor assigned successfully.",
    professorAssignError: "Failed to assign professor. Please try again.",
    professorRemoveSuccess: "Professor removed successfully.",
    professorRemoveError: "Failed to remove professor. Please try again.",
  },
  memberships: {
    listEmpty: "No memberships found.",
    colPlan: "Plan",
    colStatus: "Status",
    colHours: "Hours",
    colStart: "Start",
    colExpires: "Expires",
    colActions: "Actions",
    actionView: "View",
    actionValidatePayment: "Validate Payment",
    actionActivate: "Activate",
    txLoading: "Loading transactions...",
    txEmpty: "No transactions recorded yet.",
    txColType: "Type",
    txColDelta: "Delta",
    txColReason: "Reason",
    txColActor: "Actor",
    txColDate: "Date",
    adminPageTitle: "Memberships",
    adminNewButton: "New Membership",
    adminFilterAll: "All",
    adminLoading: "Loading memberships...",
    detailBreadcrumb: "Memberships",
    detailBreadcrumbDetail: "Detail",
    detailLoading: "Loading membership...",
    detailTitle: "Membership",
    detailSectionDetails: "Details",
    detailSectionTxHistory: "Hour Transaction History",
    detailLabelPlan: "Plan",
    detailLabelProgram: "Program",
    detailLabelStudent: "Student",
    detailLabelPurchasedHours: "Purchased hours",
    detailLabelAvailableHours: "Available hours",
    detailLabelStartDate: "Start date",
    detailLabelExpirationDate: "Expiration date",
    detailLabelPaymentValidated: "Payment validated",
    detailLabelActivatedAt: "Activated at",
    detailLabelCreatedAt: "Created at",
    detailLabelUpdatedAt: "Updated at",
    btnValidateActivate: "Validate & Activate",
    btnValidateDelegate: "Validate (delegate)",
    btnActivate: "Activate",
    btnAdjustHours: "Adjust Hours",
    adjustTitle: "Manual Hour Adjustment",
    adjustDeltaLabel: "Delta (positive = add, negative = subtract)",
    adjustDeltaPlaceholder: "e.g. 3 or -2",
    adjustZeroError: "Delta cannot be zero",
    adjustReasonLabel: "Reason",
    adjustReasonHint: "(5–500 characters, required)",
    adjustReasonPlaceholder: "Describe the reason for this adjustment...",
    adjustReasonMinError: "Reason must be at least 5 characters",
    adjustSaveBtn: "Apply Adjustment",
    adjustSavingBtn: "Saving...",
    formPlanLabel: "Plan",
    formPlanSelectPlaceholder: "— Select a plan —",
    formModalityHoursBased: "Hours-based",
    formModalityClassesPerWeek: "Classes per week",
    formModalityLabel: "Modality: ",
    formHoursLabel: "Hours: ",
    formCostLabel: "Cost: ",
    formStartDateLabel: "Start date",
    formExpiresHint: "Membership expires on the last day of the selected month.",
    formPaymentValidated: "Payment already validated",
    formActivateDirectly: "Activate directly (skip manager delegation)",
    formCreateBtn: "Create Membership",
    formCreatingBtn: "Creating...",
    formSelectProgram: "— Select a program —",
    formProgramLabel: "Program enrollment",
    newPageTitle: "Create Membership",
    newBreadcrumb: "New",
    newLoadingStudent: "Loading student…",
    newNoEnrollments: "This student has no active program enrollments. Enroll them in a program first.",
    newLoadingPlans: "Loading plans…",
    newNoPlans: "No active HOURS_BASED plans found for this program.",
  },
  notifications: {
    bellAriaLabel: "Notifications",
    badgeMax: "10+",
    dropdownTitle: "Notifications",
    markAllRead: "Mark all read",
    dropdownLoading: "Loading…",
    dropdownEmpty: "No notifications.",
    viewAll: "View all",
    tabAll: "All",
    tabUnreadOnly: "Unread only",
    markAllAsRead: "Mark all as read",
    listEmpty: "No notifications found.",
    pageTitle: "Notifications",
  },
  tenants: {
    pageTitle: "Tenants",
    createButton: "Create New League",
    filterStatusLabel: "Status:",
    filterAll: "All",
    filterActive: "Active",
    filterInactive: "Inactive",
    listLoading: "Loading tenants...",
    listEmpty: "No tenants found",
    colName: "Name",
    colSlug: "Slug",
    colDiscipline: "Discipline",
    colStatus: "Status",
    colCreatedAt: "Created At",
    detail: {
      labelDiscipline: "Discipline",
      labelLanguage: "Language",
      labelContactEmail: "Contact Email",
      labelContactPhone: "Contact Phone",
      labelAddress: "Address",
      labelCreatedAt: "Created At",
      labelCreatedBy: "Created By",
      labelDeactivatedAt: "Deactivated At",
      labelDeactivatedBy: "Deactivated By",
      languageSpanish: "Spanish",
      languageEnglish: "English",
      deactivateButton: "Deactivate Tenant",
      deactivateConfirmText: "Are you sure? This will invalidate all sessions.",
      deactivateConfirm: "Confirm Deactivation",
      deactivating: "Deactivating...",
      deactivateSuccess: "Tenant has been deactivated successfully.",
      deactivateError: "Failed to deactivate tenant. Please try again.",
    },
    form: {
      labelName: "Name",
      labelDiscipline: "Discipline",
      labelLanguage: "Language",
      labelSlug: "Slug",
      slugAutoFill: "(auto-filled from name)",
      slugPreview: "Preview:",
      labelContactEmail: "Contact Email",
      legendContactAddress: "Contact Address",
      labelStreet: "Street Address",
      labelCity: "City",
      labelState: "State / Dept.",
      labelCountry: "Country",
      labelContactPhone: "Contact Phone",
      phoneSelectCountryFirst: "Select a country first",
      phoneSelectCountryHint: "Select a country to enable this field.",
      languagePlaceholder: "Select language...",
      languageSpanish: "Spanish",
      languageEnglish: "English",
      submitButton: "Create Tenant",
      submitting: "Creating...",
      errorNameRequired: "Name is required.",
      errorDisciplineRequired: "Discipline is required.",
      errorLanguageRequired: "Language is required.",
      errorSlugRequired: "Slug is required.",
      errorContactEmailRequired: "Contact email is required.",
      errorContactEmailInvalid: "Enter a valid email address.",
      errorCountryRequired: "Country is required.",
      errorContactPhoneRequired: "Contact phone is required.",
      errorContactPhoneInvalid: "Phone must contain digits only.",
      errorStreetRequired: "Street address is required.",
      errorCityRequired: "City is required.",
      errorStateRequired: "State is required.",
      errorLogoRequired: "Logo is required.",
      errorUnexpected: "An unexpected error occurred. Please try again.",
    },
  },
  paymentProofs: {
    pageTitle: "Payment Proof Queue",
    pageSubtitle: "Review and validate pending payment proofs.",
    queueLoading: "Loading queue…",
    queueEmpty: "No pending proofs.",
    colStudent: "Student",
    colIdDocument: "ID Document",
    colPlan: "Plan",
    colUploaded: "Uploaded",
    colType: "Type",
    colReview: "Review",
    reviewBtn: "Review",
    reviewModalTitle: "Review Payment Proof",
    planDetailsTitle: "Plan Details",
    labelProgram: "Program: ",
    labelPlan: "Plan: ",
    labelHours: "Hours: ",
    labelCost: "Cost: ",
    previewLoading: "Loading preview…",
    activateDirectlyLabel: "Activate membership directly",
    activateDirectlyHint: "(uncheck to delegate to manager)",
    approveBtn: "Approve",
    approvingBtn: "Processing…",
    rejectBtn: "Reject",
    confirmRejectBtn: "Confirm Reject",
    rejectingBtn: "Processing…",
    rejectionReasonLabel: "Rejection reason",
    rejectionReasonPlaceholder: "Explain why this proof is being rejected…",
    backBtn: "Back",
    panelTitle: "Payment Proof",
    noProofYet: "No proof uploaded yet.",
    viewApprovedProof: "View approved proof",
    gettingLink: "Getting link…",
    rejectionReasonTitle: "Rejection reason:",
    uploadNewProof: "Upload a new proof",
    uploadProof: "Upload proof",
    fileHint: "PDF, JPG, or PNG · Max 5 MB",
    fileSizeError: "File exceeds the 5 MB size limit.",
    fileTypeError: "Unsupported file type. Please upload a PDF, JPG, or PNG.",
    reviewYourFile: "Review your file before submitting",
    cancelBtn: "Cancel",
    submitBtn: "Submit proof",
    submittingBtn: "Uploading…",
    delegatedColStudent: "Student",
    delegatedColProgram: "Program",
    delegatedColDelegated: "Delegated",
    delegatedActivateBtn: "Activate",
    delegatedEmpty: "No memberships awaiting your activation.",
    delegatedLoading: "Loading delegated memberships…",
  },
  badges: {
    membershipStatus: {
      EXPIRED: "Expired",
      INACTIVE: "Inactive",
      PENDING_PAYMENT: "Pending Payment",
      PENDING_PAYMENT_VALIDATION: "Under Review",
      PENDING_MANAGER_ACTIVATION: "Pending Activation",
      ACTIVE: "Active",
    },
    proofStatus: {
      PENDING: "Pending Review",
      APPROVED: "Approved",
      REJECTED: "Rejected",
      SUPERSEDED: "Superseded",
    },
    registrationStatus: {
      REGISTERED: "Registered",
      CANCELLED_BY_STUDENT: "Cancelled",
      CANCELLED_BY_SYSTEM: "Cancelled (System)",
      SESSION_CANCELLED: "Cancelled by league",
      PRESENT: "Present",
      PRESENT_NO_HOURS: "Present (No Hours)",
      ABSENT: "Absent",
    },
    sessionStatus: {
      SCHEDULED: "Scheduled",
      ALERTED: "Scheduled",
      CANCELLED: "Cancelled",
    },
    classLevel: {
      BEGINNER: "Beginner",
      INTERMEDIATE: "Intermediate",
      ADVANCED: "Advanced",
      OPEN: "Open",
    },
    classType: {
      RECURRING: "Recurring",
      ONE_TIME: "One-Time",
    },
    enrollmentLevel: {
      BEGINNER: "Beginner",
      INTERMEDIATE: "Intermediate",
      ADVANCED: "Advanced",
    },
    professorStatus: {
      INVITED: "Invited",
      ACTIVE: "Active",
      DEACTIVATED: "Deactivated",
    },
    studentStatus: {
      ACTIVE: "Active",
      INACTIVE: "Inactive",
    },
    hourTransactionType: {
      ATTENDANCE_DEDUCTION: "Attendance",
      MANUAL_ADDITION: "Manual +",
      MANUAL_SUBTRACTION: "Manual −",
    },
  },
};

function Wrapper({ children }: { children: React.ReactNode }) {
  return (
    <NextIntlClientProvider locale="en" messages={testMessages}>
      {children}
    </NextIntlClientProvider>
  );
}

export function renderWithIntl(ui: React.ReactElement, options?: Omit<RenderOptions, "wrapper">) {
  return render(ui, { wrapper: Wrapper, ...options });
}
