ALTER TABLE audit_log DROP CONSTRAINT chk_audit_action_type;

ALTER TABLE audit_log ADD CONSTRAINT chk_audit_action_type CHECK (action_type IN (
    'TENANT_CREATED', 'TENANT_DEACTIVATED',
    'PROGRAM_CREATED', 'PROGRAM_UPDATED', 'PROGRAM_DEACTIVATED', 'PROGRAM_REACTIVATED'
));
