-- V068: extend audit_log and notifications constraints with level-change cancellation types (RF-36)

-- ── audit_log ────────────────────────────────────────────────────────────────
ALTER TABLE audit_log DROP CONSTRAINT chk_audit_action_type;
ALTER TABLE audit_log ADD CONSTRAINT chk_audit_action_type CHECK (action_type IN (
    -- Tenants
    'TENANT_CREATED',
    'TENANT_DEACTIVATED',
    -- Programs
    'PROGRAM_CREATED',
    'PROGRAM_UPDATED',
    'PROGRAM_DEACTIVATED',
    'PROGRAM_REACTIVATED',
    -- Plans
    'PLAN_CREATED',
    'PLAN_UPDATED',
    'PLAN_DEACTIVATED',
    'PLAN_REACTIVATED',
    -- Professors
    'PROFESSOR_CREATED',
    'PROFESSOR_UPDATED',
    'PROFESSOR_DEACTIVATED',
    'PROFESSOR_REACTIVATED',
    -- Classes
    'CLASS_CREATED',
    'CLASS_UPDATED',
    'CLASS_DEACTIVATED',
    'CLASS_REACTIVATED',
    'CLASS_PROFESSOR_ASSIGNED',
    'CLASS_PROFESSOR_REMOVED',
    -- Students
    'STUDENT_CREATED',
    'STUDENT_UPDATED',
    'STUDENT_DEACTIVATED',
    'STUDENT_REACTIVATED',
    'STUDENT_ENROLLED',
    'STUDENT_LEVEL_CHANGED',
    'STUDENT_UNENROLLED',
    'STUDENT_PROMOTED',
    -- Memberships
    'MEMBERSHIP_CREATED',
    'MEMBERSHIP_PAYMENT_VALIDATED',
    'MEMBERSHIP_ACTIVATED',
    'MEMBERSHIP_PENDING_MANAGER_ACTIVATION',
    'MEMBERSHIP_DEPLETED',
    'MEMBERSHIP_EXPIRED',
    'MEMBERSHIP_EXPIRY_WARNING',
    'MEMBERSHIP_HOUR_ADJUSTED',
    'MEMBERSHIP_PROOF_UPLOADED',
    'MEMBERSHIP_RENEWED',
    -- Payment Proofs
    'PAYMENT_PROOF_UPLOADED',
    'PAYMENT_PROOF_APPROVED',
    'PAYMENT_PROOF_REJECTED',
    'MEMBERSHIP_ACTIVATION_DELEGATED',
    'DELEGATION_REMINDER_SENT',
    -- Auth
    'AUTH_LOGIN',
    'AUTH_LOGOUT',
    'AUTH_REFRESH_TOKEN',
    'AUTH_LOGIN_FAILED',
    'AUTH_ACCOUNT_LOCKED',
    'AUTH_ACCOUNT_UNLOCKED',
    'AUTH_EMAIL_VERIFIED',
    'AUTH_VERIFICATION_RESENT',
    'AUTH_PASSWORD_RESET_REQUESTED',
    'AUTH_PASSWORD_RESET_COMPLETED',
    'STUDENT_SELF_REGISTERED',
    -- RBAC
    'ROLE_ASSIGNED',
    -- Attendance
    'ATTENDANCE_REGISTERED',
    'ATTENDANCE_REGISTRATION_CANCELLED',
    -- Attendance marking (RF-25, RF-26)
    'ATTENDANCE_MARKED_PRESENT',
    'ATTENDANCE_MARKED_ABSENT',
    'ATTENDANCE_MARKED_PRESENT_NO_HOURS',
    'ATTENDANCE_CORRECTED',
    -- Session lifecycle (RF-27, RF-28)
    'SESSION_ALERT_RAISED',
    'SESSION_ALERT_UPDATED',
    'SESSION_CANCELLED',
    'ATTENDANCE_REGISTRATION_CANCELLED_BY_SESSION',
    -- Level change (RF-36)
    'ATTENDANCE_REGISTRATION_CANCELLED_BY_LEVEL_CHANGE'
));

-- ── notifications ─────────────────────────────────────────────────────────────
ALTER TABLE notifications DROP CONSTRAINT chk_notification_type;
ALTER TABLE notifications ADD CONSTRAINT chk_notification_type CHECK (type IN (
    'CLASS_SESSION_ALERTED',
    'CLASS_SESSION_CANCELLED',
    'CLASS_LEVEL_CHANGED'
));
